using Platformer.Gameplay;
using UnityEngine;
using static Platformer.Core.Simulation;


namespace Platformer.Mechanics
{
    /// <summary>
    /// This class contains the data required for implementing token collection mechanics.
    /// It does not perform animation of the token, this is handled in a batch by the 
    /// TokenController in the scene.
    /// </summary>
    [RequireComponent(typeof(Collider2D))]
    public class TokenInstance : MonoBehaviour
    {
        void OnTriggerEnter2D(Collider2D other)
        {
            //only exectue OnPlayerEnter if the player collides with this token.
            var player = other.gameObject.GetComponent<PlayerController>();
            if (player != null)
            {
                ScoreSystem.instance.AddScore();
                var CollectedSound = GetComponentInChildren<AudioSource>();
                CollectedSound.Play();
                GetComponent<SpriteRenderer>().enabled = false;
                Destroy(this.gameObject, 1.0f);
            }
        }
    }
}